### ISSUE TITLE
Move entity changes to trait

### ISSUE THREAD

**Issue by JoppeDC** [JoppeDC/SyliusBetterSeoPlugin#2]
In order to provide the most flexibility, the changes we made to the product entity should be done using a trait. This way, when a user overrides the Sylius Product model, all they have to do is add the trait to get the required fields.

**Comment by reliq** [comment]
I could tackle this one

**Comment by JoppeDC** [comment]
Sure. Shouldn’t be too much work 😉

**Comment by reliq** [comment]
I am having an issue getting set up with this. Any idea why I would get this error?

---

```bash
yarn run v1.16.0
$ gulp build
[19:02:34] Requiring external module babel-register
[19:02:35] Using gulpfile /var/www/SyliusBetterSeoPlugin/tests/Application/gulpfile.babel.js
[19:02:35] Starting 'build'...
[19:02:35] Starting 'buildAdmin'...
[19:02:35] Starting 'buildShop'...
[19:02:35] 'buildAdmin' errored after 20 ms
[19:02:35] Error: File not found with singular glob: /var/www/SyliusBetterSeoPlugin/tests/Application/../../vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/gulpfile.babel.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (events.js:288:20)
    at Glob.emit (events.js:200:13)
    at Glob.EventEmitter.emit (domain.js:471:20)
    at Glob._finish (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/glob/glob.js:197:8)
    at done (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/glob/glob.js:182:14)
    at Glob._processSimple2 (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/glob/glob.js:688:12)
    at /var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/glob/glob.js:764:12)
[19:02:35] 'build' errored after 34 ms
[19:02:35] The following tasks did not complete: buildShop
[19:02:35] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by JoppeDC** [comment]
@reliq my fault, this wasn't in the readme. In the plugin root folder, you need to `composer install` all dependencies first 😉

I've also adjusted the readme with this step.

**Comment by reliq** [comment]
OK great. Thank you

**Comment by reliq** [comment]
I came to another screeching halt with this error:

```bash
yarn run v1.16.0
$ gulp build
[20:02:25] Requiring external module babel-register
[20:02:26] Using gulpfile /var/www/SyliusBetterSeoPlugin/tests/Application/gulpfile.babel.js
[20:02:26] Starting 'build'...
[20:02:26] Starting 'buildAdmin'...
[20:02:26] Starting 'buildShop'...
[gulp-chug] Gulpfile, gulpfile.babel.js, contents is empty. Reading directly from disk...
[20:02:26] 'buildAdmin' errored after 54 ms
[20:02:26] Error in plugin 'gulp-chug'
Message:
    Problem finding locally-installed `gulp` for gulpfile undefined. (Try running `npm install gulp` from /var/www/SyliusBetterSeoPlugin/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle to install a local gulp for said gulpfile.)

Error: Cannot find module 'gulp' from '/var/www/SyliusBetterSeoPlugin/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle'
    at Function.module.exports [as sync] (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/resolve/lib/sync.js:74:15)
    at DestroyableTransform._transform (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/gulp-chug/index.js:117:61)
    at DestroyableTransform.Transform._read (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/var/www/SyliusBetterSeoPlugin/tests/Application/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:200:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:494:23) {
  code: 'MODULE_NOT_FOUND'
}
Details:
    domainEmitter: [object Object]
    domainThrown: false
[20:02:26] 'build' errored after 58 ms
[20:02:26] The following tasks did not complete: buildShop
[20:02:26] Did you forget to signal async completion?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Nevertheless I made the changes: https://github.com/JoppeDC/SyliusBetterSeoPlugin/pull/8
