### ISSUE TITLE
500 error with taxon override

### ISSUE THREAD

**Issue by BideoGemu** [JoppeDC/SyliusBetterSeoPlugin#26]
Hi, I install the plugin on my Sylius test website, I read the docs and when I override Taxon I've got a 500 error on my server.

Log of the error : 
```
[2020-12-10T15:17:44.012086+01:00] php.CRITICAL: Error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't1.seo_id' in 'field list' in /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115 Stack trace: #0 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute() #1 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1255): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(750): Doctrine\DBAL\Connection->executeQuery() #3 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(768): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load() #4 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(159): Doctrine\ORM\Persisters\Entity\Basic {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't1.seo_id' in 'field list' in /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115\nStack trace:\n#0 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute()\n#1 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1255): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(750): Doctrine\\DBAL\\Connection->executeQuery()\n#3 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(768): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->load()\n#4 /mnt/j/Professionel/Developpement/casaya/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(159): Doctrine\\ORM\\Persisters\\Entity\\Basic at /mnt/j/Professionel/Developpement/casaya/vendor/sylius/resource-bundle/src/Component/Model/TranslatableTrait.php:53)"} []
```

IMHO I don't have the seo_id on taxon table, I think something done wrong when I do my `doctrine:migrations:migrate` but I don't find where the problem.

My Version20201210132508.php after my `doctrine:migrations:diff` : 
```<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201210132508 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sylius_product ADD seo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sylius_product ADD CONSTRAINT FK_677B9B7497E3DD86 FOREIGN KEY (seo_id) REFERENCES joppedc_seo (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_677B9B7497E3DD86 ON sylius_product (seo_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sylius_product DROP FOREIGN KEY FK_677B9B7497E3DD86');
        $this->addSql('DROP INDEX UNIQ_677B9B7497E3DD86 ON sylius_product');
        $this->addSql('ALTER TABLE sylius_product DROP seo_id');
    }
}
```

Is someone can help me please?

**Comment by JoppeDC** [comment]
Hi @BideoGemu . I've had someone contact me with a similar issue last week, and it had to do with doctrine caching the entities.
Could you try clearing (or even hard clearing `rm -rf var/cache/*`) the cache locally before generating migrations?

**Comment by BideoGemu** [comment]
Thanks for your time @JoppeDC, I'll try to soft and hard cache clearing but it doesn't work anymore.

It say me the table already exists so I think I go to try to create a new branch of my project and I'll retry to execute the migration. If it's work, I closed this issue. I do too many manipulations to try to debug it and so even if it work now I don't know if it going to work tomorrow.

**Comment by BideoGemu** [comment]
So, I'll retry with a proper installation and it's work, I think is a conflict with another plugin. Thanks for your help @JoppeDC.
